basePath: /v2
definitions:
  domain.Mutation:
    properties:
      pix_key:
        type: string
    type: object
host: leakyBucket
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a leaky bucket project
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /mutation:
    post:
      consumes:
      - application/json
      description: Attempts to process a mutation request, checking rate limits via
        the Leaky Bucket algorithm.
      parameters:
      - description: Mutation Request Data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.Mutation'
      produces:
      - application/json
      responses:
        "200":
          description: Request processed successfully
          schema:
            type: string
        "429":
          description: Rate limit exceeded (Leaky Bucket)
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Process Leaky Bucket Mutation
      tags:
      - Gateway
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
